spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8088"

---
spring:
  config:
    import: "optional:configserver:http://config-server:8088"
    activate:
      on-profile: docker